version: "3.3"
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                BUILD_VERSION: 'development'
        environment:
            SERVER_NAME: ${SERVER_NAME}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            SECRET_KEY: ${SECRET_KEY}
            DOMAIN: ${DOMAIN:-localhost:3000}
            OIDC_SERVER_METADATA_URL: ${OIDC_SERVER_METADATA_URL}
            OIDC_SCOPE: ${OIDC_SCOPE}
            OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
            OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
        volumes:
            - "./backend:/app"
        ports:
            - "5000:80"
        depends_on:
            - db

    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - "./data/postgres:/var/lib/postgresql/data/"
